name: Build and deploy container app to Azure Web App - ArpyDuel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_8761a1b1b91f47ac93b476c454c4cf66 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e6dbc77a970f42d4b6bb084a20eff1e2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_8761a1b1b91f47ac93b476c454c4cf66 }}/appsvc/staticsite:${{ github.sha }}
        file: ./dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ArpyDuel'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a346af35eff74a039722a1f8e1b2c574 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_8761a1b1b91f47ac93b476c454c4cf66 }}/appsvc/staticsite:${{ github.sha }}'
